stages:
  - static
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
  
eslint:
  stage: static
  script:
    - npm install -g eslint
    - eslint "./lib/*.js"

gulp:
  stage: build
  script:
    - npm install
    - gulp build

test:
  stage: test
  script:
    - npm test
    
deploy:
  stage: deploy
  script:
    - echo "no deploy now"
  